---
- hosts: all

  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: install node_exporter
      apt:
        name: prometheus-node-exporter
        state: present